#! /usr/bin/env bash

#PBS -N regrid
#PBS -q regular
#PBS -l select=4:ncpus=9:mpiprocs=9
#PBS -l walltime=08:00:00
#PBS -A CESM0005


. /glade/u/apps/ch/opt/lmod/7.2.1/lmod/lmod/init/bash

module purge

module load ncarenv/1.2

module load intel/17.0.1

module load ncarcompilers/0.4.1

module load mpt/2.15f

module load python/2.7.13

source /glade/u/home/mickelso/CESM_postprocessing_2//cesm-env2/bin/activate

module load numpy/1.12.0

module load scipy/0.18.1

module load mpi4py/2.0.0-mpt

module load pynio/1.4.1

module load matplotlib/2.0.0

module load netcdf/4.4.1.1

module load nco/4.6.2

module load netcdf4-python/1.2.7

module load cf_units/1.1.3

module load numpy/1.13.3

today="$(date '+%Y%m%d-%H%M%S')"


mpiexec_mpt dplace ./run -6 ocn_vars.txt -2 POP_gx1v7_to_latlon_1x1_0E_mask_conserve_20181015.nc -3 POP_gx1v7_to_latlon_1x1_0E_fulldepth_conserve_20181015.nc -5 POP_gx1v7_to_latlon_1x1_0E_partialdepth_conserve_20190121.nc -i /glade/collections/cdg/cmip6/15/  -c 10 >> /gpfs/fs1/work/cmip6/cases/b.e21.BHIST.f09_g17.CMIP6-historical.001/postprocess/logs/ocn.remap.log.$today 2>&1

